# Generated by Django 4.1.4 on 2023-03-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Credentials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ways',
        ),
    ]
