# Generated by Django 4.1.4 on 2023-03-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ways',
            options={'verbose_name': 'way', 'verbose_name_plural': 'ways'},
        ),
        migrations.RemoveField(
            model_name='ways',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ways',
            name='slug',
        ),
    ]
