# Generated by Django 4.1.4 on 2023-03-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_bank', '0002_alter_ways_options_remove_ways_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ways',
            options={},
        ),
        migrations.AlterField(
            model_name='ways',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
